[versions]
kotlin = "1.9.20"
ksp = "1.9.20-1.0.14"
ktlint = "1.0.1"
moshi = "1.15.0"
dagger = "2.48.1"

[libraries]
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"

jda = "net.dv8tion:JDA:5.0.0-beta.17"

okio = "com.squareup.okio:okio:3.6.0"

moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }

javax-inject = "javax.inject:javax.inject:1"
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }

[plugins]
shadow = "com.github.johnrengelman.shadow:8.1.1"
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = "io.github.mfederczuk.ktlint:0.1.0-indev08"
