name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master, develop/github-actions ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 22

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Checkout Repository
        uses: actions/checkout@v4

      - run: ./gradlew build :main:createExecutable
