name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 22

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gradle
        run: ./gradlew --project-prop=buildType=development build :main:createExecutable
