name: Create Pre-Release Draft

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-indev[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

jobs:
  create-prerelease:
    name: Create Pre-Release Draft ${{ github.ref_name }}

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 22

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Save version name
        run: |
          tag_name="$GITHUB_REF_NAME"
          tag_name="${tag_name#v}"
          printf 'CZD_BOT_VERSION_NAME=%s\n' "$tag_name" >> "$GITHUB_ENV"

      - name: Run Gradle
        run: ./gradlew build :main:createGzippedExecutable

      - name: Create pre-release draft ${{ github.ref_name }}
        uses: softprops/action-gh-release@v2
        with:
          name: Version ${{ env.CZD_BOT_VERSION_NAME }}
          prerelease: true
          fail_on_unmatched_files: true
          files: czd-bot-*.gz
          draft: true
