#!/bin/sh
# -*- sh -*-
# vim: syntax=sh
# code: language=shellscript

#region preamble

case "$-" in
	(*'i'*)
		\command printf 'script was called interactively\n' >&2
		return 124
		;;
esac

set -o errexit
set -o nounset

# enabling POSIX-compliant behavior for GNU programs
export POSIXLY_CORRECT=yes POSIX_ME_HARDER=yes

if [ "${0#/}" = "$0" ]; then
	argv0="$0"
else
	argv0="$(basename -- "$0" && printf x)"
	argv0="${argv0%"$(printf '\nx')"}"
fi
readonly argv0

#endregion

if [ $# -gt 0 ]; then
	printf '%s: too many arguments: %i\n' "$argv0" $# >&2
	exit 4
fi

if ! command -v gzip > '/dev/null'; then
	printf '%s: gzip: program missing\n' "$argv0" >&2
	exit 27
fi


root_dir_pathname="$(dirname -- "$0" && printf x)"
root_dir_pathname="${root_dir_pathname%"$(printf '\nx')"}"
root_dir_pathname="$(dirname -- "$root_dir_pathname")"
root_dir_pathname="$(dirname -- "$root_dir_pathname")"
readonly root_dir_pathname

packages_dir_pathname="$root_dir_pathname/packages"
readonly packages_dir_pathname

main_dist_dir_pathname="$root_dir_pathname/main/build/distributions"
readonly main_dist_dir_pathname


"$root_dir_pathname/gradlew" :main:distTar --no-configuration-cache --no-build-cache --no-daemon --parallel --stacktrace

tar_archive_pathname=''
for f in "$main_dist_dir_pathname/"*'.tar'; do
	if [ -n "$tar_archive_pathname" ]; then
		printf '%s: %s: multiple tar archives\n' "$argv0" "$main_dist_dir_pathname" >&2
		exit 48
	fi

	tar_archive_pathname="$f"
done
readonly tar_archive_pathname


tar_gz_archive_pathname="$(basename -- "$tar_archive_pathname")"
tar_gz_archive_pathname="$packages_dir_pathname/$tar_gz_archive_pathname.gz"
readonly tar_gz_archive_pathname

rm -rf -- "$packages_dir_pathname"
mkdir -p -- "$packages_dir_pathname"
gzip -9kc -- "$tar_archive_pathname" > "$tar_gz_archive_pathname"
