name: Publish Release

on:
  push:
    tags: [ v*.*.* ]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 22

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Checkout Repository
        uses: actions/checkout@v4

      - run: ./gradlew build :main:createGzippedExecutable

      - uses: softprops/action-gh-release@v2
        with:
          files: czd-bot-*.gz
